$schema: https://json-schema.org/draft-07/schema#
title: PlayerVoiceFramework Pack-Config Schema
description: Schema for the Pack-File
type: object
properties:
  settings:
    type: object
    description: General Settings
      #properties:

  events:
    type: array
    description: Sound Events to register
    items:
      type: object
      properties:
        name:
          type: string
          description: The name of the event
        chance:
          type: integer
          description: Chance for the event to play
          minimum: 1
          maximum: 100
        cooldown:
          type: integer
          description: Cooldown of this event, in seconds
          minimum: 0
        overrideBlacklist:
          type: array
          description: A list of event names that when playing cannot get replaced
            by this event
          items:
            type: string
          uniqueItems: true
        audios:
          type: array
          description: A list of audio packs. The first pack that has a matching condition
            will be played.
          items:
            type: object
            properties:
              condition:
                type: string
                description: "Code-Like Condition-Expression. Example: PlayerRace == 'Nord' && PlayerStaminaPercentage < 50"
              files:
                type: array
                description: List of relative (from this config) paths to the wav
                  files.
                items:
                  type: string
                minItems: 1
            required:
              - files
      required:
        - name
        - audios