name: Build Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        shell: cmd
        run: |
          reg add "HKLM\SOFTWARE\Wow6432Node\Bethesda Softworks\Skyrim Special Edition" /v "Installed Path" /t REG_SZ /d "%GITHUB_WORKSPACE%" /f
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -DCMAKE_BUILD_TYPE=Release --preset release -S . -B build/release

      - name: Build Project
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call buildscripts/build-plugin.bat
          call buildscripts/compile-papyrus-scripts.bat

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: PlayerVoiceEvents-Nightly
          if-no-files-found: warn
          path: |
            Scripts
            Seq
            SKSE
            Sound
            LICENSE
            PVE-Events.jsonc
            PVE-Conditions.jsonc
            PlayerVoiceEvents.esp
