name: Build Mod

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -DCMAKE_BUILD_TYPE=Release --preset release -S . -B build/release
          cmake --build build/release --target all -j 14