name: Build Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        shell: cmd
        run: |
          reg add "HKLM\SOFTWARE\Wow6432Node\Bethesda Softworks\Skyrim Special Edition" /v "Installed Path" /t REG_SZ /d "%GITHUB_WORKSPACE%" /f
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=ninja.exe  --preset release -S . -B build/release

      - name: Build Project
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call buildscripts/build-plugin.bat
          call buildscripts/compile-papyrus-scripts.bat
          call buildscripts/create-release.bat

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ github.run_number }}
          release_name: PlayerVoiceEvents-Nightly ${{ github.run_number }}
          body: |
            This has been automatically built by GitHub Actions.
          draft: false
          prerelease: true

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/PlayerVoiceEvents.zip
          tag_name: nightly-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}