name: Build CommonLibSSE-NG Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup VCPKG environment
        run: |
          mkdir vcpkg && cd vcpkg
          git clone https://github.com/microsoft/vcpkg.git .
          ./bootstrap-vcpkg.bat
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Configure CMake Presets
        run: cmake --preset release
        env:
          CMAKE_TOOLCHAIN_FILE: ${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build Plugin
        run: cmake --build build/release --config Release

      - name: Copy DLL's
        run: |
          mkdir "SKSE/Plugins"
          copy "build/release/PlayerVoiceEvents.dll" "SKSE/Plugins/"
          copy "build/release/PlayerVoiceEvents.pdb" "SKSE/Plugins/"
        shell: pwsh

      - name: Setup Pyro
        run: |
          .\setup-pyro.bat
        shell: pwsh

      - name: Compiling Papyrus Scripts
        run: |
          .\pyro\pyro.exe --input-path skyrimse.ppj --compiler-path "Papyrus Compiler/PapyrusCompiler.exe"
        shell: pwsh

      - name: Creating Release
        run: |
          .\create-release.bat
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PlayerVoiceEvents-Nightly
          path: release/PlayerVoiceEvents.zip